In [1]:
# print(data.shape) # 크기
# print(data.dtype) # 데이터 타입
# print(data.ndim) # 차원

In [2]:
#[과제] 인덱싱을 이용하여 아래 벼열을 내림차순으로 정렬하세요.

In [4]:
# 삼항식의 벡터화 버젼
import numpy as np
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0, 2, -2)


[[-0.77821062 -1.05580419 -0.57829314  1.73738147]
 [-0.60084704  0.15318717  0.54660313 -0.46841339]
 [ 0.38877306  0.21516011  0.43004926 -0.07335931]
 [-1.13266243 -0.05371574 -0.13423924 -0.35840851]] 



array([[-2, -2, -2,  2],
       [-2,  2,  2, -2],
       [ 2,  2,  2, -2],
       [-2, -2, -2, -2]])

In [2]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = list(range(10))
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
c = np.random.randn(2,3)
c * 10

array([[ -6.85534507,  14.08346099, -17.59771744],
       [ -2.39576268,  -5.07416905,  -3.38977563]])

In [11]:
c.shape

(2, 3)

In [12]:
c.dtype

dtype('float64')

In [13]:
c.ndim

2

In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ndim)
print(arr.dtype)
print(arr.shape)

2
int32
(2, 4)


In [17]:
np.zeros((1,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [21]:
np.full((2,4,3),7)

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

In [3]:
np.eye(5,6,3)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
a = np.arange(15)
b = a.reshape(3,5)
c = a.reshape(3,1,5)
c

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [38]:
a = np.arange(10)
b = a.reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
a = np.arange(30)
print(a,a.shape,a.dtype,a.ndim)
b = a.reshape(2,15)
print(b,b.shape,b.dtype,b.ndim)
c = b.reshape(2,5,3)
print(c,c.shape,c.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) int32 1
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] (2, 15) int32 2
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]] (2, 5, 3) 3


In [50]:
a = np.arange(30)
b = a.reshape(5,-1)
c = b.reshape(-1,5,3)
print(b)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [52]:
a = np.arange(30)
b = a.reshape(-1,6)
c = b.reshape(-1)
d = b.reshape(3,5,-1)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


In [31]:
np.full((4,4,4),7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [6]:
a = np.eye(5,4,2)
a

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros(25).reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
a = np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [29]:
b =a.astype(float)
b

array([1., 2., 3.])

In [33]:
np.empty(shape=(10,))
# np.zeros(shape=(10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
a =np.array([1,2,3,4], dtype = 'S')
a

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [38]:
a.astype(float)

array([1., 2., 3., 4.])

In [42]:
list_e = [1.2,2.3,3]
a = np.array(list_e)
b = a.astype(int)
b

array([1, 2, 3])

In [43]:
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
b * b

array([1, 4, 9])

In [46]:
b - b

array([0, 0, 0])

In [51]:
a >= a

array([ True,  True,  True])

In [58]:
np.random.seed(0)
np.random.randn(5,5)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462]])

In [60]:
np.random.randn(5,5).mean().round(2)

-0.28

In [76]:
np.random.randn(3,5).mean(axis=1)

array([-0.34180417,  0.40410411, -0.11409091])

In [77]:
np.random.randn(3,5).sum().round(3)

-1.169

In [91]:
np.arange(10).reshape(2,-1)[:-1,1]


array([1])

In [93]:
a = np.arange(30).reshape(6,-1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [101]:
a[2,2:5]
a[0:2,3]
a[:3,1]

array([ 1,  6, 11])

In [105]:
li = a.tolist()
type(li)

list

In [109]:
a = np.arange(10)
print(a)
b = a[a > 4]
print(b)
print(a > 5)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[False False False False False False  True  True  True  True]


In [112]:
a[6:]

array([6, 7, 8, 9])

In [114]:
a = np.arange(1,15)
b = a[(a/2) > 5]
print(b)
print((a/2) > 5)

[11 12 13 14]
[False False False False False False False False False False  True  True
  True  True]


In [115]:
names = np.array(['a','b','c','d','a','b','c','d'])
data = np.random.randn(8,3)
print(names)
print(data)

['a' 'b' 'c' 'd' 'a' 'b' 'c' 'd']
[[-0.51751904 -0.97882986 -0.43918952]
 [ 0.18133843 -0.5028167   2.41245368]
 [-0.96050438 -0.79311736 -2.28862004]
 [ 0.25148442 -2.01640663 -0.53945463]
 [-0.27567053 -0.70972797  1.73887268]
 [ 0.99439439  1.31913688 -0.88241882]
 [ 1.12859406  0.49600095  0.77140595]
 [ 1.02943883 -0.90876325 -0.42431762]]


In [116]:
names == 'b'

array([False,  True, False, False, False,  True, False, False])

In [121]:
data[names == 'b', 1:]

array([[-0.5028167 ,  2.41245368],
       [ 1.31913688, -0.88241882]])

In [122]:
data[names != 'b']

array([[-0.51751904, -0.97882986, -0.43918952],
       [-0.96050438, -0.79311736, -2.28862004],
       [ 0.25148442, -2.01640663, -0.53945463],
       [-0.27567053, -0.70972797,  1.73887268],
       [ 1.12859406,  0.49600095,  0.77140595],
       [ 1.02943883, -0.90876325, -0.42431762]])

In [132]:
data[data <0] = 0
data

array([[0.        , 0.        , 0.        ],
       [0.18133843, 0.        , 2.41245368],
       [0.        , 0.        , 0.        ],
       [0.25148442, 0.        , 0.        ],
       [0.        , 0.        , 1.73887268],
       [0.99439439, 1.31913688, 0.        ],
       [1.12859406, 0.49600095, 0.77140595],
       [1.02943883, 0.        , 0.        ]])

In [143]:
a = np.arange(10)
print(a)
b = np.zeros_like(a).reshape(2,1,5)
print(b,b.dtype)
c = np.ones_like(b).astype(float)
print(c,c.dtype)
d = np.full_like(c,5).reshape(2,-1).astype('int64')
print(d,d.dtype)

[0 1 2 3 4 5 6 7 8 9]
[[[0 0 0 0 0]]

 [[0 0 0 0 0]]] int32
[[[1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]]] float64
[[5 5 5 5 5]
 [5 5 5 5 5]] int64


In [156]:
for i in range(1,101):
    if i % 3 == 0:
        print(i,end=" ")
a = np.arange(1,101)
print()
print(a[a%3==0])
np.arange(3,101,3)

3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [158]:
for i in range(1,101):
    if i % 10 == 0:
        print(i,end=" ")
print()
print(np.arange(10,101,10))

10 20 30 40 50 60 70 80 90 100 
[ 10  20  30  40  50  60  70  80  90 100]


In [187]:
print(np.random.randn(1000,100).mean())
print(np.random.randn(1000,100).std())

-0.003148942581611798
0.9991328282417247


In [189]:
np.__version__

'1.21.2'

In [191]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [195]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [197]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [208]:
a = [1,2,0,0,4,0]
b = np.array(a)
b.nonzero()

(array([0, 1, 4], dtype=int64),)

In [211]:
a = np.empty((8,4))
for i in range(8):
    a[i] = i
a

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [214]:
a[[-6,-1,-3]]

array([[2., 2., 2., 2.],
       [7., 7., 7., 7.],
       [5., 5., 5., 5.]])

In [215]:
a.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [223]:
a = np.random.randint(1,10,(5,7))
print(a)
print(a.T)
print(np.swapaxes(a,0,1))
print(np.transpose(a.T))

[[7 6 6 1 4 9 2]
 [3 8 9 9 3 5 9]
 [3 5 3 6 2 3 3]
 [4 1 4 4 7 4 5]
 [9 9 3 9 7 9 3]]
[[7 3 3 4 9]
 [6 8 5 1 9]
 [6 9 3 4 3]
 [1 9 6 4 9]
 [4 3 2 7 7]
 [9 5 3 4 9]
 [2 9 3 5 3]]
[[7 3 3 4 9]
 [6 8 5 1 9]
 [6 9 3 4 3]
 [1 9 6 4 9]
 [4 3 2 7 7]
 [9 5 3 4 9]
 [2 9 3 5 3]]
[[7 6 6 1 4 9 2]
 [3 8 9 9 3 5 9]
 [3 5 3 6 2 3 3]
 [4 1 4 4 7 4 5]
 [9 9 3 9 7 9 3]]


In [1]:
a = np.arange(1,101).reshape(10,10)
a[[1,3,5,7,9]] = a[[1,3,5,6,9]][:,::-1]
a

NameError: name 'np' is not defined

In [4]:
import numpy as np
np.eye(3,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.empty(3)

array([1., 1., 1.])

In [16]:
a = np.arange(1,101).reshape(10,10)
a[[1,3,5,7,9]] = a[[1,3,5,7,9]][:,::-1]
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91]])

In [21]:
a = np.ones(10).astype(int)
a[[1,3,5,7,9]] = 0
print(a)

[1 0 1 0 1 0 1 0 1 0]


In [28]:
a = np.arange(10)
a[-4:]

array([6, 7, 8, 9])

In [31]:
a = np.ones((10,10))
a[1:9,1:9] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
import random
random.randint(10,20)

10

In [40]:
np.random.rand(10)

array([0.4635668 , 0.06706541, 0.83870932, 0.74127329, 0.36666938,
       0.41379473, 0.04641125, 0.02786342, 0.91193639, 0.63149402])

In [48]:
a = np.arange(16).reshape(2,2,4)
print(a,a.shape)
b = np.transpose(a,(1,0,2))
print(b,b.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4)


In [51]:
c = np.transpose(a,(0,2,1))
c.shape

(2, 4, 2)

In [56]:
a = np.ones((5,5))
b = np.zeros((9,9))
b[2:7,2:7] = a
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [57]:
a = np.zeros((8,8))
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])