Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공

- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

Numpy 특징
- 강력한 N차원 배열 객체
- 정교한 브로드케스팅 기능
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [2]:
!pip install numpy

In [2]:
import numpy as np
z = np.arange(10)
print(z,type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [11]:
my_arr = np.arange(1000)
print(my_arr.dtype)
my_list = list(range(1000))
print(my_list.type)

int32


AttributeError: 'list' object has no attribute 'type'

In [5]:
%time for _ in range(10): my_array2 = my_arr * 2

Wall time: 11.9 ms


In [6]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 597 ms


In [10]:
# 배열 연산
# np.random.randn 가우시안 표준 정규분표에서 난수 매트릭스 array 생성
data = np.random.randn(2,3) # 표준 정규분포로 구성되는 2행 3열  매트릭스
print(data,'\n')
print(data * 10, '\n')
print(data + data)

[[-1.08663197 -1.05722898 -0.15848285]
 [-0.68136296 -0.32553937  0.08877524]] 

[[-10.86631966 -10.5722898   -1.58482848]
 [ -6.81362964  -3.25539367   0.88775239]] 

[[-2.17326393 -2.11445796 -0.3169657 ]
 [-1.36272593 -0.65107873  0.17755048]]


In [12]:
print(data.shape) # 크기
print(data.dtype) # 데이터 타입
print(data.ndim) # 차원

(2, 3)
float64
2


다차원 배열
<img src = 'numpy차원.jpg' STYLE = 'width:300px;'>

In [20]:
data2 = [[1,2,3,4],[5,6,7,8]]
print(type(data2))
arr2 = np.array(data2)
print(arr2,type(arr2))

<class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [23]:
print(arr2.ndim,'\n')
print(arr2.shape)

2 

(2, 4)


In [26]:
# 1차원 배열로 3개의 데이터 
array1 = np.array([1,2,3])
print(array1,type(array1),array1.shape) # (,열)이 아닌 (열,) 형태로 출력

[1 2 3] <class 'numpy.ndarray'> (3,)


In [28]:
# 2차원 배열로 2개의 row와 3개의 column으로 구성된 6개의 데이터
array2 = np.array([[1,2,3],[4,5,6]])
print(array2,type(array2),array2.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [30]:
#1개의 row와 3개의 column으로 구성된 2차원 배열

array3 = np.array([[1,2,3]])
print(array3,array3.shape)

[[1 2 3]] (1, 3)


In [39]:
# 3차원
array4 = np.array([[[1,2,3,4],[4,5,6,7]],
                   [[1,2,3,4],[4,5,6,7]],
                   [[1,2,3,4],[4,5,6,7]]])
print(array4,array4.shape,'\n')
print(type(array4))

[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]] (3, 2, 4) 

<class 'numpy.ndarray'>


In [41]:
# 미래의 오류가 표시될때 경고 메세지 제외 처리
import warnings
warnings.filterwarnings('ignore')

배열 생성 및 초기화
- Numpy 는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like  함수도 제공

In [45]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [50]:
print(np.ones(10),'\n')
print(np.ones((3,6)),'\n')
print(np.ones((2,3,2),dtype=int))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [12]:
ar1 = np.full((2,2,2),5)
ar1

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

In [49]:
# 항등행렬, 단위행렬
ar2 = np.eye(3)
ar2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

In [51]:
# arange 함수 : python의 range 함수의 배열 버젼
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
arr2 = arr1.reshape(3,5)
print(arr2, arr2.shape, '\n')
arr3 = arr1.reshape(1,3,5)
print(arr3, arr3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]] (1, 3, 5)


In [58]:
# Q. array1을 생성하고 reshape 함수를 이용, (5,2) 배열을 생성하고 크기를 같이 출력하세요.
array1 = np.arange(10)
brr2 = array1.reshape(5,2)
print(brr2, brr2.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


In [62]:
# 0~29 일차원 배열을 생성한 후 다시 2, 3차원 배열로 변환하여 출력하세요.
brr1 = np.arange(30)
brr2 = brr1.reshape(6,5)
brr3 = brr1.reshape(3,5,2)
print(brr2,brr2.shape,'\n')
print(brr3,brr3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] (6, 5) 

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]] (3, 5, 2)


In [67]:
# reshape(-1, -1) 이용, 차원 변경
array1 = np.arange(30)
ar12 = array1.reshape(3,-1)
print(ar12,ar12.shape,'\n')
ar13 = array1.reshape(-1,2,5)
print(ar13,ar13.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


In [73]:
# 2 -> 1, 3차원으로 변환
arr12 = ar12.reshape(30,)
print(arr12,arr12.shape,'\n')
arr13 = ar12.reshape(3,2,5)
print(arr13,arr13.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


In [76]:
# 3 -> 1,2차원으로 변환
a1 = arr13.reshape(-1,)
a2 = arr13.reshape(-1,5)
print(a1,a1.shape,'\n')
print(a2,a2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] (6, 5)


행렬의 종류
- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을 때 항등행렬이 나오는 행렬

In [78]:
# 정방행렬
a = np.full((5,5), 7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [80]:
#항등행렬, 단위행렬
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
# 영행렬
a = np.zeros(25)
a.reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

ndarray 데이터 형태 지정 및 변경
<img src = '데이터형태.jpg' STYLE = 'width:300px;'>

In [88]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype = np.int32)
print(arr1,arr1.dtype, '\n')
print(arr2,arr2.dtype)

[1. 2. 3.] float64 

[1 2 3] int32


In [17]:
#타입 변경
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(complex)
print(float_arr.dtype)

int32
complex128


In [18]:
# empty 함수 : shape와 dtype을 입력 받아 초기화되지 않은 배열을 만들어준다.
# ch, zeros 함수, empty 함수를 실행할 때마다 값이 다른 것을 확인할 수 있다.
# 이는 해당 메모리 영역에 어떤 데이터가 남아있었던지 상관 없이 그대로 
# 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 때문임.
print(np.empty(shape=(10,), dtype=np.int8))
print(np.zeros(shape=(10,), dtype=np.int8))

[  96 -128   52  -36 -121    2    0    0    0    0]
[0 0 0 0 0 0 0 0 0 0]


In [101]:
# 문자열 타입으로 배열 만들기
# arr = np.array([1,2,3,4], dtype = 'S')
arr = np.array([1,2,3,4], dtype = np.string_)
print(arr, arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [100]:
arr1 = arr.astype(int)
print(arr1, arr1.dtype)

[1 2 3 4] int32


In [105]:
# 정수와 실수로 구성된 list_e = [1.2,2.3,3]을 numpy를 이용해서 실수형과 정수형으로 각각 출력하세요.
list_e = [1.2,2.3,3]
ar1 = np.array(list_e)
print(ar1,ar1.dtype,'\n')
ar2 = ar1.astype(int)
print(ar2,ar2.dtype)

[1.2 2.3 3. ] float64 

[1 2 3] int32


In [107]:
#배열의 산술 연산
# arr = np.array([[1,2,3],[4,5,6]])
arr = np.arange(1,7).reshape(2,3)
print(arr,arr.dtype)

[[1 2 3]
 [4 5 6]] int32


In [109]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [110]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [112]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [113]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [118]:
#기본 사칙연산
value1 = np.arange(1,10).reshape(3,3)
value2 = np.arange(11,20).reshape(3,3)
print(value2 + value1)
print(np.add(value1,value2),'\n')
print(value2 - value1)
print(np.subtract(value2,value1),'\n')
print(value2 * value1)
print(np.multiply(value2,value1),'\n')
print(value2 / value1)
print(np.divide(value2,value1))

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]
[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [19]:
arr = np.random.randn(5,4)
arr

array([[-1.42320899,  1.47823735, -0.79262128,  0.73278972],
       [ 1.98999549, -1.12800342,  0.52352392,  0.46380275],
       [ 0.36786603, -0.49947687, -1.14158944,  0.91579452],
       [ 1.22528459,  1.46911156,  0.53672832, -0.96923918],
       [-0.12813917,  1.26871341, -1.60548295, -0.17565872]])

In [124]:
arr.mean().round(4)

0.1192

In [126]:
arr.mean(axis=1)

array([-0.0093985 ,  0.17693187,  0.23990881,  0.01002379,  0.17868984])

In [129]:
arr.mean(axis = 0)

array([-0.11074882,  0.06758738,  0.423481  ,  0.09660509])

In [131]:
arr.sum().round(4)

2.3846

In [20]:
arr.cumprod()

array([-1.42320899, -2.10384069,  1.6675489 ,  1.22196269,  2.43170023,
       -2.74296618, -1.43600841, -0.66602465, -0.24500784,  0.12237575,
       -0.13970286, -0.12793912, -0.15676183, -0.23030062, -0.12360886,
        0.11980655, -0.01535191, -0.01947718,  0.03127027, -0.0054929 ])

In [4]:
# 인덱싱,슬라이싱
import numpy as np 
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
arr2d[2]

array([7, 8, 9])

In [137]:
arr2d[2][2]

9

In [138]:
arr2d[:,0]

array([1, 4, 7])

In [18]:
# arr2d[:2,:]
# arr2d[:-1,:]
arr2d[[0,1],:]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#arr2d에서 [3,6],[[1,2],[4,5]]을 출력하세요.
print(arr2d[:2,2])
arr2d[:2,:-1]

[3 6]


array([[1, 2],
       [4, 5]])

In [21]:
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
# [14,15,16]
# [3,9]
# [1,7,13]
print(arr[2][2:5])
print(arr[[0,1],3])
print(arr[:3,1])

[14 15 16]
[3 9]
[ 1  7 13]


In [35]:
# 배열을 리스트로 변환
li = arr.tolist()
print(li,type(li))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] <class 'list'>


In [39]:
# Boolean indexing
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d > 5]
print(arr3)
print(arr1d > 5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [44]:
# arr1d에서 일반 인덱스를 이용해서 [6,7,8,9]를 출력하세요.
arr1d[5:10]

array([6, 7, 8, 9])

In [49]:
# Q. 1 ~ 14까지 ndarray를 만들어 array_e로 저장하고 (array_e / 2) > 5를 만족하는 값을 불린 인덱싱으로 출력하세요.
array_e = np.arange(1,15)
print(array_e)
arr1 = array_e[(array_e / 2) > 5]
print(arr1)
print((array_e / 2) > 5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[11 12 13 14]
[False False False False False False False False False False  True  True
  True  True]


In [7]:
import numpy as np
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(names,'\n')
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 

[[ 1.09907394 -0.73365459 -1.45537204 -0.10613761]
 [ 0.12252082  0.89045874 -1.94605985 -0.92414691]
 [-0.12447351  0.63806833  0.46924491  0.73388391]
 [ 0.05133911  0.71351599 -0.52448364 -1.40100851]
 [ 1.06688549 -1.00766067  0.29481749  0.06895679]
 [ 0.08625435 -1.263962   -0.54981201 -0.4435836 ]
 [ 1.64142248  1.47088515 -0.8740015   1.1183332 ]]


In [51]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [53]:
data[names == 'Bob']

array([[-0.76051153,  0.55827999, -0.20038931,  1.14993151],
       [-0.26142812, -1.17697412, -1.77137225, -0.46389973]])

In [56]:
data[names == 'Bob', 2:]

array([[-0.20038931,  1.14993151],
       [-1.77137225, -0.46389973]])

In [58]:
# != 부정
data[names != 'Bob']

array([[ 0.60658324,  0.50628461, -0.34245409,  0.4430109 ],
       [-0.55153046,  0.00517933, -1.05655711,  0.79233867],
       [-0.09304154, -0.45398073, -0.56128693, -0.76677063],
       [ 0.10499636, -0.00953215,  1.26075879,  0.97640409],
       [ 0.50460549, -0.75410121, -0.34548798, -0.38561091]])

In [68]:
# 'Bob'이거나 'Will'인 것 출력
mask = (names == 'Bob') | (names == 'Will')
data[mask]
# data[(names == 'Bob') | (names == 'Will')]

array([[-0.76051153,  0.55827999, -0.20038931,  1.14993151],
       [-0.55153046,  0.00517933, -1.05655711,  0.79233867],
       [-0.26142812, -1.17697412, -1.77137225, -0.46389973],
       [-0.09304154, -0.45398073, -0.56128693, -0.76677063]])

In [70]:
# 음수를 모두 0으로 처리하여 출력
data[data < 0] = 0
print(data)

[[0.         0.55827999 0.         1.14993151]
 [0.60658324 0.50628461 0.         0.4430109 ]
 [0.         0.00517933 0.         0.79233867]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.10499636 0.         1.26075879 0.97640409]
 [0.50460549 0.         0.         0.        ]]


In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
ar1 = np.zeros_like(a)
ar2 = ar1.astype(float)
print(ar2, ar2.dtype)
print()
ar3 = np.ones_like(a)
ar4 = ar3.astype(float)
print(ar4, ar4.dtype)
print()
ar5 = np.full_like(a, 6)
ar6 = ar5.astype('float32')
print(ar6, ar6.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] float64

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]] float32


In [3]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.
a = np.array([1,2,3,4,5])
print(np.zeros_like(a))
print(np.ones_like(a))
print(np.full_like(a,3))

[0 0 0 0 0]
[1 1 1 1 1]
[3 3 3 3 3]


In [6]:
# [과제] 1~ 100까지 정수에서 3의 배수인 것만을 출력 (for문과 배열 두가지방식)
n = []
for i in range(1,101):
    if i % 3 == 0:
        n.append(i)
print(n)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


In [7]:
arr=np.arange(1,101)
print(arr[arr%3==0])



arr_li=arr.tolist()
for i in arr_li:
    if i%3==0:
        print(i,end=" ")


[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 

In [98]:
import numpy as np
arr = np.arange(3,101,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [100]:
#[과제] 1~100까지 정수에서 5의 배수이면서 2의 배수인것만을 출력(for문과 배열 두가지 방식)
n=[]
for i in range(1,101):
    if i % 10 ==0:
        n.append(i)
print(n)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [8]:
import numpy as np
arr = np.arange(10,101,10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [9]:
li = []
for i in range(1,101):
    if i % 5 == 0 and i % 2 == 0:
        li.append(i)
print(li)
        
arr = np.arange(1,101)
arr2 = arr[arr % 10 == 0]
print(arr2)


[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
[ 10  20  30  40  50  60  70  80  90 100]


In [13]:
#[과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.
import numpy as np
a = np.random.randn(10000,10000)
print(a)
print(a.mean())
print(a.std())

[[-8.98818049e-01 -1.74479402e+00 -4.47883209e-01 ... -1.18585820e+00
  -3.80743297e-01 -5.10176904e-01]
 [ 2.29910950e-01 -2.16483738e+00 -2.60829271e+00 ...  3.02013219e+00
   2.64068754e-02  1.79522067e-01]
 [ 6.43333880e-01 -2.37842864e+00  1.22334726e+00 ... -5.86304816e-01
   2.20332134e+00 -3.19116290e-01]
 ...
 [ 4.63855005e-01  1.56364319e+00  3.01876781e-03 ...  1.74508776e+00
   1.34763626e-02 -5.72395208e-02]
 [-7.28968546e-01  1.08175920e-01 -4.90347299e-01 ...  9.84127326e-01
   9.16704647e-01 -6.65118611e-01]
 [ 7.68582038e-01  7.82771730e-01 -1.14562282e+00 ... -9.25429736e-02
  -1.28162171e+00 -2.84965216e-01]]
-0.00011442633389702241
0.9999872929447784


In [14]:
# [과제] 현재 사용하고 있는 numpy의 버전을 출력하세요.
# !pip show numpy
import numpy
print(numpy.__version__)
np.__version__

1.21.2


'1.21.2'

In [15]:
# [과제] numpy 함수의 도움말 기능을 볼 수 있는 방법을 수행하여 add함수의 가이드를 출력하세요.
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [16]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [18]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력하세요.
# array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
a = np.zeros(10)
print(a)
np.add.at(a,[4],1)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
arr = np.zeros([10])
arr[4]=1
arr


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [20]:
#[과제] 인덱싱을 이용하여 아래 벼열을 내림차순으로 정렬하세요.
import numpy as np
li = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
li_rev = np.sort(li)[::-1]
print(li_rev)

[9 8 7 6 5 4 3 2 1 0]


In [21]:
arr = np.arange(10)
print(arr[::-1])


[9 8 7 6 5 4 3 2 1 0]


In [25]:
arr=np.array([1,2,0,0,4,0])
print(arr[arr != 0])


[1 2 4]


In [22]:
#[과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.
import numpy as np
a = np.array([1,2,0,0,4,0])
print(a.nonzero())

(array([0, 1, 4], dtype=int64),)


In [26]:
a= np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [30]:
# Fancy Indexing
import numpy as np
arr = np.empty((8,4))
print(arr)
for i in range(8):
    arr[i] = i
arr

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [32]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [34]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [37]:
arr = np.arange(32).reshape((8,4))
print(arr,'\n')

arr[[1,5,7,2],[0,3,1,2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 



array([ 4, 23, 29, 10])

In [42]:
print(arr[[1,5,7,2]],'\n')
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [45]:
# 배열 전치와 축 바꾸기
import numpy as np
arr = np.arange(15).reshape(3,5)
print(arr,'\n')
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
