In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10, size=(5,5))
arr

array([[6, 2, 7, 1, 8],
       [3, 2, 5, 5, 7],
       [8, 4, 2, 7, 8],
       [3, 5, 7, 3, 3],
       [1, 6, 7, 2, 5]])

In [5]:
# 전치
arr.T
np.transpose(arr)

array([[6, 3, 8, 3, 1],
       [2, 2, 4, 5, 6],
       [7, 5, 2, 7, 7],
       [1, 5, 7, 3, 2],
       [8, 7, 8, 3, 5]])

In [6]:
# 행렬곱, 내적
np.dot (arr.T, arr)

array([[119,  71, 101,  88, 147],
       [ 71,  85, 109,  67, 107],
       [101, 109, 176,  81, 163],
       [ 88,  67,  81,  88, 118],
       [147, 107, 163, 118, 211]])

In [10]:
a = np.arange(6).reshape(2,3)
print(a,'\n')

y = np.swapaxes(a, 0,1) # 0은 2차원(열), 1은 1차원(행)
print(y,'\n')

y = a.T
y = np.transpose(a)
print(y)

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]]


In [19]:
# 1~100을 아래와 같이 출력하세요.
arr = np.arange(1,101)
arr1 = arr.reshape(10,10)
print(arr1[0])
print(arr1[1,::-1])
print(arr1[2])
print(arr1[3,::-1])
print(arr1[4])
print(arr1[5,::-1])
print(arr1[6])
print(arr1[7,::-1])
print(arr1[8])
print(arr1[9,::-1])

[ 1  2  3  4  5  6  7  8  9 10]
[20 19 18 17 16 15 14 13 12 11]
[21 22 23 24 25 26 27 28 29 30]
[40 39 38 37 36 35 34 33 32 31]
[41 42 43 44 45 46 47 48 49 50]
[60 59 58 57 56 55 54 53 52 51]
[61 62 63 64 65 66 67 68 69 70]
[80 79 78 77 76 75 74 73 72 71]
[81 82 83 84 85 86 87 88 89 90]
[100  99  98  97  96  95  94  93  92  91]


In [21]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(arr)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [22]:
a = np.arange(1, 101).reshape((10, -1))

for i in range(10):
    if i % 2 == 1:
        a[i] = a[i][::-1]

print(a)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [32]:
# (0,1,2)
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) -> (2,1,3)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,0,2))
print(y,y.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0 1 2]]

 [[3 4 5]]] (2, 1, 3)


In [33]:
# (1,2,3) -> (2,3,1)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,2,0))
print(y,y.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


In [40]:
# 나머지를 구할 경우 사용하는 함수
value1= np.array([15,30,45])
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))

[1 2 0]
[1 2 0]


In [44]:
# 각 수의 역수를 구해주는 함수
value = np.array([0.85, 1.85, 1, 100])
print(np.reciprocal(value),'\n')

value1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1, dtype = float))

[1.17647059 0.54054054 1.         0.01      ] 

[100] 

[0.01]


In [45]:
# 승수의 결과 값을 표시해주는 함수
value1 = np.array([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))

[  4 100 225] 

[   2  100 3375]


In [2]:
import numpy as np
arr = np.random.randn(10)
print(arr.mean(),'\n')
print(arr.std())
arr

0.6617060246545815 

0.8595235693777018


array([-0.16152214,  1.49393102,  0.4430447 ,  1.86588377,  0.2252329 ,
        0.93936094, -0.39523516, -0.13603552,  0.1763726 ,  2.16602713])

In [53]:
# 양수인 원소의 개수
(arr > 0).sum()

4

In [55]:
# 하나 이상의 값이 True인지 검사
bools = np.array([False,False,True,True])
bools.any()

True

In [56]:
# 모든 원소가 True인지 검사
bools.all()

False

In [58]:
# 삼항식의 벡터화 버젼
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0, 2, -2)


[[ 0.34541309  0.11326651  0.47728937 -0.020818  ]
 [-0.85114427 -0.6489264   1.03275254  0.62459837]
 [-0.02016008  0.10980239  0.30083616 -0.34518019]
 [ 0.74292572  0.71697239 -1.41838109 -0.22408034]] 



array([[ 2,  2,  2, -2],
       [-2, -2,  2,  2],
       [-2,  2,  2, -2],
       [ 2,  2, -2, -2]])

In [61]:
# arr의 모든 양수를 2로 바꿀 경우
np.where(arr > 0, 2, arr )

array([[ 2.        ,  2.        ,  2.        , -0.020818  ],
       [-0.85114427, -0.6489264 ,  2.        ,  2.        ],
       [-0.02016008,  2.        ,  2.        , -0.34518019],
       [ 2.        ,  2.        , -1.41838109, -0.22408034]])

In [63]:
# 두개의 1차원 배열을 받아서 가능한 모든 (x,y) 짝을 만들 수 있는 2차원 배열 2개 반환
x = np.arange(1,4)
y = np.arange(1,4)
xs,ys = np.meshgrid(x,y)
print(xs,'\n')
print(ys)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [6]:
# np.sort()
import numpy as np
np.random.seed(0)
arr = np.random.randint(1,100,size=10)
print(arr,'\n')
print(np.sort(arr),'\n')
print(arr)

[45 48 65 68 68 10 84 22 37 88] 

[10 22 37 45 48 65 68 68 84 88] 

[45 48 65 68 68 10 84 22 37 88]


In [8]:
sorted = np.sort(arr)
print(sorted)

[10 22 37 45 48 65 68 68 84 88]


In [11]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행, 열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,1]])
print(arr2d,'\n')
sort_ar2d_axis0 = np.sort(arr2d, axis = 0)
print(sort_ar2d_axis0,'\n')
sort_ar2d_axis1 = np.sort(arr2d, axis = 1)
print(sort_ar2d_axis1,'\n')

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]] 



In [17]:
# ndarray.sort() : 원본 반영
np.random.seed(0)
arr = np.random.randint(1,10,size= 10)
print(arr,'\n')
print(np.sort(arr)) # 원본 반영


[6 1 4 4 8 4 6 3 5 8] 

[1 3 4 4 4 5 6 6 8 8]


In [23]:
# 다차원 배열의 정렬은 sort  메소드에 넘긴 축에 따라 1차원 부분을 정렬
#열방향 정렬, default
np.random.seed(0)
arr = np.random.randint(1,10,size= (5,3))
print(arr,'\n')
arr.sort() # 1을 줘도 됨
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[1 4 6]
 [4 4 8]
 [3 5 6]
 [7 8 9]
 [2 7 9]]


In [3]:
#행방향 정렬
import numpy as np
np.random.seed(0)
arr = np.random.randint(1,10,size= (5,3))
print(arr,'\n')
arr.sort(0) 
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[4 1 4]
 [6 2 4]
 [6 3 5]
 [8 7 7]
 [9 8 9]]


In [26]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할때
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
print(type(sort_indices))
sort_indices

[3 1 9 5]
<class 'numpy.ndarray'>


array([1, 0, 3, 2], dtype=int64)

In [43]:
#배열에서 정렬한 후 5% 분위수에 해당되하는 원소만 출력
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]

-1.6383970335303657

In [45]:
# 배열 집합 연산 
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [3]:
import numpy as np
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

['Bob', 'Joe', 'Will']

In [4]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [6]:
# 배열 데이터의 입출력
# np.save, np.ioad는 바이너리 형식 .npy 파일로 저장
arr = np.arange(10)
np.save('some_array',arr)

In [7]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz', a = arr, b = arr)

In [10]:
arch = np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0] 을 출력하세요.
a = np.ones(10,dtype=int)
np.add.at(a,[1,3,5,7,9],-1)
print(a)

[1 0 1 0 1 0 1 0 1 0]


In [51]:
a = np.ones(10).astype(int)
a[[1,3,5,7,9]] = 0
print(a)


[1 0 1 0 1 0 1 0 1 0]


In [31]:
# Q. a = np.arange(10)에서 [6,7,8,9] 출력
a = np.arange(10)
print(a[6:])

[6 7 8 9]


In [32]:
a = np.arange(10)
print(a[a>5].tolist())


[6, 7, 8, 9]


In [33]:
# Q. a에서 최대값, 최소값 출력
print(max(a))
print(min(a))

9
0


In [42]:
# Q. a에서 최대값, 최소값 인덱스 출력
a = np.arange(1,10)
print(np.argmax(a))
print(np.argmin(a))

8
0


In [43]:
# Q. a에서 인덱스 배열을 역순으로 출력하세요.
np.argsort(a)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [56]:
# Q. np.ones((10,10))을 아래와 같이 출력하세요.
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
b=np.ones((10,10))
b[1:9,1:9]=0
b


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

[파이썬 random 함수]

In [65]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li, 3), '\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.33395875931254093 

3 

19.155207244032994 

9 

1 

[3, 2, 4] 

[4, 3, 2, 5, 1]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1 사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [72]:
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개 
print(np.random.randint(1,20), '\n') # 1 ~ 19 까지 정수인 난수 1개
print(np.random.randint(10, size = 10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size = 10), '\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size = (3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

4 

18 

[7 6 7 9 7 2 7 5 3 0] 

[14 12 17 14 11 15 13 14 17 13] 

[[17 16 19 11 19]
 [11 12 14 16 13]
 [12 13 11 10 16]]


In [74]:
r = np.random.rand(6) # 0 ~ 1 사이의 균일분포
print(r,'\n')
r.mean()

[0.51276389 0.15124964 0.66445955 0.78602064 0.74794061 0.07776602] 



0.4900333902125795

In [133]:
# 표준 정규 분포
r = np.random.randn(10000)
print(r,'\n')
r.mean()

[ 0.01070648 -0.85993063  0.89027304 ...  0.56468555  1.2599697
 -0.96511194] 



0.017327478309223182

In [79]:
list = np.arange(1,6)
print(list)
np.random.shuffle(list)
list

[1 2 3 4 5]


array([2, 4, 3, 5, 1])

In [80]:
np.random.choice(list)

5

In [81]:
a = np.array([11,11,3,3,2,2,2,7])
index,count = np.unique(a,return_counts=True)
print(index)
print(count)

[ 2  3  7 11]
[3 2 1 2]


In [82]:
np.random.uniform(1.0, 2.0, 10)

array([1.83346196, 1.33240447, 1.8449896 , 1.03353178, 1.71245607,
       1.01243059, 1.22927785, 1.06075868, 1.41059799, 1.75676426])

In [84]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최대값을 각각 0, 1로 지정한 것과 같음.
np.random.random_sample((2,3))

array([[0.40231226, 0.70591466, 0.19899333],
       [0.68811923, 0.45966291, 0.04809842]])

In [85]:
!pip install pandas

In [86]:
ar = np.random.rand(4,8)
ar

array([[0.03120435, 0.96095773, 0.08811864, 0.64622274, 0.69758711,
        0.35519548, 0.87306192, 0.00276165],
       [0.8626455 , 0.91785861, 0.92801633, 0.25508034, 0.04172351,
        0.8102142 , 0.83424931, 0.45658443],
       [0.78802695, 0.60746895, 0.55219469, 0.28127776, 0.07692676,
        0.4769781 , 0.11295348, 0.2111481 ],
       [0.02797855, 0.56218544, 0.8596535 , 0.44486041, 0.2106364 ,
        0.19782418, 0.78992131, 0.98147214]])

In [91]:
# 배열을 데이터프레임으로 변환
import pandas as pd
df = pd.DataFrame(ar)
print(df,type(df))

          0         1         2         3         4         5         6  \
0  0.031204  0.960958  0.088119  0.646223  0.697587  0.355195  0.873062   
1  0.862645  0.917859  0.928016  0.255080  0.041724  0.810214  0.834249   
2  0.788027  0.607469  0.552195  0.281278  0.076927  0.476978  0.112953   
3  0.027979  0.562185  0.859653  0.444860  0.210636  0.197824  0.789921   

          7  
0  0.002762  
1  0.456584  
2  0.211148  
3  0.981472   <class 'pandas.core.frame.DataFrame'>


In [94]:
print(df[0])
type(df[0])

0    0.031204
1    0.862645
2    0.788027
3    0.027979
Name: 0, dtype: float64


pandas.core.series.Series

In [99]:
columns = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar, index, columns = columns)
df

id    gender       age    region   product     price       qty  \
0  0.031204  0.960958  0.088119  0.646223  0.697587  0.355195  0.873062   
1  0.862645  0.917859  0.928016  0.255080  0.041724  0.810214  0.834249   
2  0.788027  0.607469  0.552195  0.281278  0.076927  0.476978  0.112953   
3  0.027979  0.562185  0.859653  0.444860  0.210636  0.197824  0.789921   

       time  
0  0.002762  
1  0.456584  
2  0.211148  
3  0.981472

In [123]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 출력하세요.
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data,np.arange(1,4),['ID','Gender','Age'])
df


ID Gender Age
1  5424      M  20
2  8391      F  22
3  2028      F  18

In [125]:
ar = np.zeros((4,3))
columns = ['id','gender','age']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df.id = np.array([1,2,3,4])
# df.id = np.arange(1,5)
df.gender = np.array([0,1,0,1])
# np.random.seed(0)
# df.gender = np.random.randint(2, size =4)
df.age = np.array([20,30,40,50])
# df.age = np.arange(1,5) * 10
df

id  gender  age
0   1       0   20
1   2       1   30
2   3       0   40
3   4       1   50

In [2]:
# [과제] 아래배열에서 3차원과 2차원을 변경하여 출력하세요.(shape 확인)
# [[[ 0  1  2  3]
#   [ 4  5  6  7]]

#  [[ 8  9 10 11]
#   [12 13 14 15]]] (2, 2, 4)
import numpy as np
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape)

y = np.transpose(arr,(1,0,2))
print(y,y.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4)


In [8]:
# [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요.(shape확인)
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape)

y = np.transpose(arr,(0,2,1))
print(y,y.shape)
arrsw = arr.swapaxes(1,2)
print(arrsw,arrsw.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2)
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2)


In [9]:
# [과제] np.ones((5,5))을 아래와 같이 출력하세요.
# array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])
b=np.ones((5,5))
a = np.zeros((9,9))

In [11]:
a=np.ones((5,5))
b=np.zeros((9,9))
b[2:7,2:7]=a
b


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
ar=np.ones((10,10))
ar[[0,1,8,9]]=0
ar[:,[0,1,8,9]]=0
print(ar)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
arr1 = np.ones((5,5))
np.pad(arr1,(2,2),'constant',constant_values=0)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
# [과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요.(두가지 방식: 인덱싱, tile함수)
# array([[0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0]])
a = np.array([[0,1],[1,0]])
b = np.tile(a,(4,4))
print(b,'\n')
x = np.zeros((8,8))
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [26]:
# [도전과제] np.arange(4)을 아래와 같이 출력하세요.
# array([[0, 0, 0, 0, 0],
#        [1, 0, 0, 0, 0],
#        [0, 2, 0, 0, 0],
#        [0, 0, 3, 0, 0],
#        [0, 0, 0, 4, 0]])
d=np.diag(np.arange(4)+1,k=-1)
print(d,'\n')

zero = np.zeros((5, 5))
a = np.arange(4)

for i in range(4):
    zero[i + 1, i] = a[i] + 1
    
print(zero)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]] 

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [23]:
# [도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하시오.
arr=np.arange(336).reshape(6,7,8)
print(np.where(arr==99),'\n')

print(np.unravel_index(99,(6,7,8)))


(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64)) 

(1, 5, 3)


[과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력하세요.(관측치 1000개) 

- id : 1 ~ 1000번 일련번호
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성
- product_19 : 제품코드 11111 ~ 99999
- product_20 : 제품코드 11111 ~ 99999
- price_19 : 1000 ~ 50000 사이 실수 난수 생성
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01 ~ 24 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_20 * quantity_20
- sales : 19년 대비 20년구매금액이 증가면 1, 감소면 0

In [27]:
import numpy as np
import pandas as pd
ar = np.zeros((1000,15))
columns = ['id', 'gender', 'age', 'region', 'product_19', 'product_20', 'price_19', 'price_20', 'quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
index = [np.arange(1,1001)]
df = pd.DataFrame(ar,index,columns = columns)
df.id = np.arange(1,1001)
np.random.seed(0)
df.gender = np.random.randint(2, size = 1000)
df.age = np.random.randint(0,81, size = 1000)
df.region = np.random.randint(1,11, size = 1000)
df.product_19 = np.random.randint(11111,100000, size = 1000)
df.product_20 = np.random.randint(11111,100000, size = 1000)
df.price_19 =  np.random.randint(1000,50001, size = 1000)
df.price_20 =  np.random.randint(1000,50001, size = 1000)
df.quantity_19 = np.random.randint(1,101, size = 1000)
df.quantity_20 = np.random.randint(1,101, size = 1000)
df.time_19 = np.random.randint(1,25, size = 1000)
df.time_20 = np.random.randint(1,25, size = 1000)
df.amount_19 = df.price_19 * df.quantity_19
df.amount_20 = df.price_20 * df.quantity_20
df.sales = df.amount_19 < df.amount_20
df

id  gender  age  region  product_19  product_20  price_19  price_20  \
1        1       0   39      10       86337       24026     38654     30705   
2        2       1   28       4       80109       27936     35903     32350   
3        3       1   24       1       61679       40872     14617     36879   
4        4       0   18       7       51043       27089     44802     32440   
5        5       1   67       4       67132       20153     48222     49878   
...    ...     ...  ...     ...         ...         ...       ...       ...   
996    996       0   46       9       29503       18727     26805     15040   
997    997       0   69       9       20582       57674      5360      5886   
998    998       0   28       6       76646       16573     29042     17194   
999    999       1   43       6       81112       49989     46785     31743   
1000  1000       0   62       4       40261       74062     23249      1161   

      quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
1              73           42       20       11    2821742    1289610  False  
2              48           77       23       22    1723344    2490950   True  
3              60            2       19       21     877020      73758  False  
4              57           94       22       10    2553714    3049360   True  
5              80           58        9       21    3857760    2892924  False  
...           ...          ...      ...      ...        ...        ...    ...  
996            52           19       17        7    1393860     285760  False  
997            19           50       21       16     101840     294300   True  
998            43           58        4       20    1248806     997252  False  
999            98           89        4       14    4584930    2825127  False  
1000           73           41       24        2    1697177      47601  False  

[1000 rows x 15 columns]

In [33]:
import numpy as np
import pandas as pd

arr = np.zeros((10,15))
col = ['ID','Gender','Age','Region','Product_19','Product_20','Price_19','Price_20',
       'Quantity_19','Quantity_20','Time_19','Time_20','Amount_19','Amount_20','Sales']
index = np.arange(1,11)
df = pd.DataFrame(arr,index,col)

p19 = np.random.uniform(1000,50001,10).round(2)
q19 = np.random.randint(1,101,size=10)
p20 = np.random.uniform(1000,50001,10).round(2)
q20 = np.random.randint(1,101,size=10)

df.ID = np.random.randint(1,1001,size=10)
df.Gender = np.random.randint(2,size=10)
df.Age = np.random.randint(80,size=10)
df.Region = np.random.randint(1,11,size=10)
df.Product_19 = np.random.randint(11111,100000,size=10)
df.Product_20 = np.random.randint(11111,100000,size=10)
df.Price_19 = p19
df.Price_20 = p20
df.Quantity_19 = q19
df.Quantity_20 = q20
df.Time_19 = np.random.randint(1,25,size=10)
df.Time_20 = np.random.randint(1,25,size=10)
df.Amount_19 = p19*q19
df.Amount_20 = p20*q20
df.Sales = np.where(df.Amount_20-df.Amount_19>0,1,0)

df

ID  Gender  Age  Region  Product_19  Product_20  Price_19  Price_20  \
1   956       1   40       4       91832       42125  49538.80  28910.75   
2   931       1    8       3       35663       17634  18519.62  47085.28   
3   620       1   21       8       29714       78011  20066.49  48364.69   
4    72       1   60       9       78975       18572  41950.45  42369.23   
5   559       0   46       7       24692       32655  31532.14  44558.13   
6   233       0   70       3       45018       31773   4482.75  45348.78   
7   357       0   78       3       60918       92382   3825.36   4751.31   
8   148       0   20      10       37398       80951  26899.57  43005.76   
9   267       1   48       6       11258       34641  20442.24  21371.29   
10  474       0   76       1       85721       81941  37036.87   3090.66   

    Quantity_19  Quantity_20  Time_19  Time_20   Amount_19   Amount_20  Sales  
1           100           62       10       12  4953880.00  1792466.50      0  
2            37           96        5       18   685225.94  4520186.88      1  
3            87           68        5        5  1745784.63  3288798.92      1  
4            27           22        1       14  1132662.15   932123.06      0  
5            28            4        8       10   882899.92   178232.52      0  
6            60           89       13       21   268965.00  4036041.42      1  
7            76           11       15        3   290727.36    52264.41      0  
8            32           69       23       18   860786.24  2967397.44      1  
9             4           72        7        4    81768.96  1538732.88      1  
10          100           15       21       13  3703687.00    46359.90      0

In [37]:
import random
import string
import warnings
warnings.filterwarnings('ignore')

arr = np.zeros((1000,15))
columns = ['id','gender','age','region','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
index = [np.arange(1000)]
df = pd.DataFrame(arr,index,columns = columns)

id_arr = np.arange(1,1001) ; np.random.shuffle(id_arr) ; df.id = id_arr
gender_ar = np.array(['남','여']) ; df.gender = np.array(np.random.choice(gender_ar) for _ in range(1000))
df.age = np.random.randint(80,size = 1000)
df.region = np.random.randint(10,size = 1000)
def code(a):
    li = []
    for _ in range(a):
        result = ""
        for _ in range(2):
            result += random.choice(string.ascii_uppercase)
        for _ in range(3):
            result += random.choice(string.digits)
        li.append(result)
    return np.array(li)
df.product_19 = code(1000)
df.product_20 = code(1000)
df.price_19 = np.random.rand(1000)*499000+1000
df.price_20 = np.random.rand(1000)*499000+1000
df.quantity_19 = np.random.randint(1,101,size=1000)
df.quantity_20 = np.random.randint(1,101,size=1000)
time_ar = []
for _ in range(1,25):                   # df.time_19 = np.random.randint(1,25,size=1000).astype(str)       # 이 방식 안돼..
    time_ar.append(f'{_}'.zfill(2))     # df.time_19 = df.time_19.str.zfill(2)
np.array(time_ar)
df.time_19 = np.array(np.random.choice(time_ar) for _ in range(1000))
df.time_20 = np.array(np.random.choice(time_ar) for _ in range(1000))
# df.time_19 = np.random.randint(1,25,size=1000)
# df.time_20 = np.random.randint(1,25,size=1000)
df.amount_19 = df.price_19 * df.quantity_19
df.amount_20 = df.price_20 * df.quantity_20
for _ in range(1000):
    if df.amount_19[_] <= df.amount_20[_]:
        df.sales[_] = 1
    else:
        df.sales[_] = 0
#pd.Series(df.sales).astype(int)
pd.options.display.float_format = '{:.2f}'.format
df

id gender  age  region product_19 product_20  price_19  price_20  \
0    730      남   53       6      DJ890      JS958  45292.07 312193.32   
1    148      여   54       3      KW578      DJ261 329169.87 363535.74   
2    555      여   43       7      DN081      BB417  38428.17 140734.44   
3     19      남   20       3      HG098      YZ270 454102.63 275715.54   
4    636      남   20       7      TL636      ZC427 110001.78  80217.60   
..   ...    ...  ...     ...        ...        ...       ...       ...   
995  629      여    9       7      KB840      DE659 408296.63 399238.55   
996  888      여   79       3      DX718      NE614 294574.22 259601.77   
997  719      남   70       8      ZU787      TR995 209705.16 394056.39   
998  810      여   59       6      WV055      QQ325 445873.21 246333.26   
999  635      남   10       4      OY933      UE013 301538.68 327042.31   

     quantity_19  quantity_20 time_19 time_20   amount_19   amount_20  sales  
0             91           58      10      19  4121578.32 18107212.59   1.00  
1             84           48      15      12 27650268.74 17449715.73   0.00  
2             55           31      09      17  2113549.09  4362767.50   1.00  
3             48           47      23      04 21796926.46 12958630.60   0.00  
4             44            8      18      12  4840078.29   641740.77   0.00  
..           ...          ...     ...     ...         ...         ...    ...  
995           64           91      16      07 26130984.46 36330707.62   1.00  
996           89           10      12      23 26217105.18  2596017.68   0.00  
997           75           63      12      02 15727886.91 24825552.84   1.00  
998           73           48      01      17 32548744.55 11823996.72   0.00  
999           50           57      09      02 15076933.93 18641411.45   1.00  

[1000 rows x 15 columns]

In [39]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd

customer = 1000

array = np.zeros((customer,14),dtype = int)
df = pd.DataFrame(array,(np.arange(1,customer+1)),columns = ['id','gender','age','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales'])
np.random.seed(0)
df.id = np.arange(1,customer+1)
df.gender = np.random.choice(['M','F'],customer)
df.age = np.random.randint(1,81,size=customer)
df.product_19 = np.random.randint(11111,100000,size = customer)
df.product_20 = np.random.randint(11111,100000,size = customer)

pricearray= np.random.randint(10,500,size = 100000)*100

for i in range(1,customer+1):
    df.price_19[i] = pricearray[df.product_19[i]]
    df.price_20[i] = pricearray[df.product_20[i]]

df.quantity_19 = np.random.randint(1,101,size = customer)
df.quantity_20 = np.random.randint(1,101,size = customer)

df.time_19 = np.random.randint(1,25,size = customer)
df.time_20 = np.random.randint(1,25,size = customer)

df.amount_19 = df.price_19*df.quantity_19
df.amount_20 = df.price_20*df.quantity_20

for i in range(1,customer+1):
    if df.amount_20[i]>df.amount_19[i]:
        df.sales[i] = 1
    else:
        df.sales[i] = 0

df.head() # 앞의 5개만 출력

id gender  age  product_19  product_20  price_19  price_20  quantity_19  \
1   1      M   40       24227       55976     42900     17000           76   
2   2      F   29       77462       78920     27400     38500           66   
3   3      F   25       53750       46507     25600     49500           55   
4   4      M   19       73611       29381     28000     19100           71   
5   5      F   68       82728       84075      1300     23200           20   

   quantity_20  time_19  time_20  amount_19  amount_20  sales  
1           79       18       20    3260400    1343000      0  
2           45        4       19    1808400    1732500      0  
3           36       24       18    1408000    1782000      1  
4           15        2       17    1988000     286500      0  
5           90        3       20      26000    2088000      1

In [41]:
df[df.sales==0]
print(len(df[df.sales ==0]))
df[df.sales == 1].head()

504


id gender  age  product_19  product_20  price_19  price_20  quantity_19  \
3   3      F   25       53750       46507     25600     49500           55   
5   5      F   68       82728       84075      1300     23200           20   
6   6      F   45       86860       40802      2400      3800           61   
7   7      F   46       28305       29878     42300     28600            3   
9   9      F    1       43834       64636     19800     18900           19   

   quantity_20  time_19  time_20  amount_19  amount_20  sales  
3           36       24       18    1408000    1782000      1  
5           90        3       20      26000    2088000      1  
6           66        4        9     146400     250800      1  
7           45       11       12     126900    1287000      1  
9           35       22       19     376200     661500      1